name = "SymCOOSolverInterface"
uuid = "ae3c181e-ed7e-43c0-ab5d-b5d0cb097c72"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
HSL = "0.1.0, 0.2.0"
LDLFactorizations = "^0.8.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
